### ISSUE TITLE
🙏 Feature Request: Stats explanation

### ISSUE THREAD

**Issue by skywall** [IGPenguin/stay-dead#2]
### 💎 It would be better if...
<img width="167" alt="Screenshot 2023-03-04 at 17 47 41" src="https://user-images.githubusercontent.com/5667370/222918459-cec898c5-dc0c-48b9-906f-c5ba4a126d91.png">

Until I looked into the code, I didn't understand the meaning of those icons/stats. Some tooltips would be nice.

**Comment by IGPenguin** [comment]
Thanks for the feedback! It's much appreciated. 

I'll definitely add an explanation once all of the core components are done and working as expected. Now it's still more of an initial prototype. 😅

**Comment by IGPenguin** [comment]
There's now a tutorial at the start of the game.
I've added also some new features and balance changes making the game easier.

Feel free to close this issue if you think it was resolved. 🙂
